### ISSUE TITLE
Support initiator email verification

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#21]
What's to stop John initiating a case pretending to be Bob? There should be a way for workflows to require the initiator verify their email address before kicking off the next step.

The way we talked about handling this was the same way other approvals happen:

``` yaml
states:
  - name: Not started
    actions:
    - name: Initiate
      handler: |
        change_state('Awaiting Verification')
        assign(data.submitter_email, send_email=True)
  - name: Awaiting verification
    actions:
    - name: Verify
      handler: |
        change_state('Awaiting Approval')
        assign(data.supervisor_email, send_email=True)
```

Should we just leave it like this? Would it make things much easier if we handled initiator verification in a first-class way? (ie. would it avoid the need to think about "claiming cases" and such)
